// デモアカウント情報

// 応募者（講師）のデモアカウント
export const demoApplicantAccounts = [
  {
    id: "applicant-1",
    name: "山田 太郎",
    email: "demo.tutor@example.com",
    password: "demotutor",
    university: "東京大学",
    faculty: "文学部",
    grade: "3年",
    applications: [
      {
        id: "app-1",
        jobId: "job-1",
        status: "pending",
        appliedAt: new Date("2023-04-15"),
        notes: "英語の指導経験あり",
      },
      {
        id: "app-2",
        jobId: "job-2",
        status: "accepted",
        appliedAt: new Date("2023-04-10"),
        notes: "数学の指導経験あり",
      },
    ],
    messages: [
      {
        id: "msg-1",
        senderId: "employer-1",
        receiverId: "applicant-1",
        content: "山田様、英語講師の応募ありがとうございます。面接日程の調整をさせていただきたいです。",
        timestamp: new Date("2023-04-16T10:30:00"),
        isRead: false,
        senderType: "employer",
      },
      {
        id: "msg-2",
        senderId: "applicant-1",
        receiverId: "employer-1",
        content: "ご連絡ありがとうございます。面接日程の調整よろしくお願いいたします。",
        timestamp: new Date("2023-04-16T11:45:00"),
        isRead: true,
        senderType: "applicant",
      },
      {
        id: "msg-3",
        senderId: "employer-1",
        receiverId: "applicant-1",
        content: "4月20日15時から可能でしょうか？オンライン面接を予定しています。",
        timestamp: new Date("2023-04-16T14:20:00"),
        isRead: false,
        senderType: "employer",
      },
      {
        id: "msg-4",
        senderId: "employer-2",
        receiverId: "applicant-1",
        content: "山田様、数学講師の採用が決定しました。詳細は追ってご連絡いたします。",
        timestamp: new Date("2023-04-12T09:15:00"),
        isRead: true,
        senderType: "employer",
      },
    ],
    unreadMessageCount: 2,
    latestMessageFrom: "スタディプラス進学塾",
  },
  {
    id: "applicant-2",
    name: "佐藤 花子",
    email: "demo.teacher@example.com",
    password: "demoteacher",
    university: "京都大学",
    faculty: "理学部",
    grade: "4年",
    applications: [
      {
        id: "app-3",
        jobId: "job-3",
        status: "accepted",
        appliedAt: new Date("2023-04-05"),
        notes: "国語の指導経験あり",
      },
    ],
    messages: [
      {
        id: "msg-5",
        senderId: "employer-2",
        receiverId: "applicant-2",
        content: "佐藤様、国語講師の採用が決定しました。勤務開始日について相談させてください。",
        timestamp: new Date("2023-04-07T13:45:00"),
        isRead: false,
        senderType: "employer",
      },
      {
        id: "msg-6",
        senderId: "applicant-2",
        receiverId: "employer-2",
        content: "ご連絡ありがとうございます。勤務開始日の相談、よろしくお願いいたします。",
        timestamp: new Date("2023-04-07T15:30:00"),
        isRead: true,
        senderType: "applicant",
      },
    ],
    unreadMessageCount: 1,
    latestMessageFrom: "アカデミア学習センター",
  },
]

// 企業（塾）のデモアカウント
export const demoEmployerAccounts = [
  {
    id: "employer-1",
    email: "demo.school@example.com",
    password: "demoschool",
    name: "スタディプラス進学塾",
    address: "東京都渋谷区道玄坂1-2-3",
    phone: "03-1234-5678",
    representative: "佐藤 一郎",
    description:
      "渋谷区を中心に展開する進学塾です。個別指導と少人数制のクラスで、生徒一人ひとりに合わせた指導を行っています。",
    status: "approved",
    createdAt: new Date("2022-12-10"),
    jobs: [
      { id: "job-1", title: "英語講師募集", status: "active", createdAt: new Date("2023-04-01") },
      { id: "job-2", title: "数学講師募集", status: "active", createdAt: new Date("2023-04-15") },
    ],
    messages: [
      {
        id: "msg-1",
        senderId: "employer-1",
        receiverId: "applicant-1",
        content: "山田様、英語講師の応募ありがとうございます。面接日程の調整をさせていただきたいです。",
        timestamp: new Date("2023-04-16T10:30:00"),
        isRead: true,
        senderType: "employer",
      },
      {
        id: "msg-2",
        senderId: "applicant-1",
        receiverId: "employer-1",
        content: "ご連絡ありがとうございます。面接日程の調整よろしくお願いいたします。",
        timestamp: new Date("2023-04-16T11:45:00"),
        isRead: false,
        senderType: "applicant",
      },
      {
        id: "msg-3",
        senderId: "employer-1",
        receiverId: "applicant-1",
        content: "4月20日15時から可能でしょうか？オンライン面接を予定しています。",
        timestamp: new Date("2023-04-16T14:20:00"),
        isRead: true,
        senderType: "employer",
      },
    ],
  },
  {
    id: "employer-2",
    email: "demo.academy@example.com",
    password: "demoacademy",
    name: "アカデミア学習センター",
    address: "東京都新宿区新宿4-5-6",
    phone: "03-9876-5432",
    representative: "田中 二郎",
    description: "新宿区を中心に展開する学習センターです。小学生から高校生まで幅広く対応しています。",
    status: "approved",
    createdAt: new Date("2023-01-15"),
    jobs: [
      { id: "job-3", title: "国語講師募集", status: "active", createdAt: new Date("2023-03-20") },
      { id: "job-4", title: "理科講師募集", status: "active", createdAt: new Date("2023-04-05") },
    ],
    messages: [
      {
        id: "msg-4",
        senderId: "employer-2",
        receiverId: "applicant-1",
        content: "山田様、数学講師の採用が決定しました。詳細は追ってご連絡いたします。",
        timestamp: new Date("2023-04-12T09:15:00"),
        isRead: true,
        senderType: "employer",
      },
      {
        id: "msg-5",
        senderId: "employer-2",
        receiverId: "applicant-2",
        content: "佐藤様、国語講師の採用が決定しました。勤務開始日について相談させてください。",
        timestamp: new Date("2023-04-07T13:45:00"),
        isRead: true,
        senderType: "employer",
      },
      {
        id: "msg-6",
        senderId: "applicant-2",
        receiverId: "employer-2",
        content: "ご連絡ありがとうございます。勤務開始日の相談、よろしくお願いいたします。",
        timestamp: new Date("2023-04-07T15:30:00"),
        isRead: false,
        senderType: "applicant",
      },
    ],
  },
]
